"""Changed File file 

Revision ID: 22627e9d9e06
Revises: f459f947512b
Create Date: 2020-07-19 10:42:44.902706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22627e9d9e06'
down_revision = 'f459f947512b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
