"""Changed File file 

Revision ID: 2aec1333954f
Revises: 42535c6e4ab1
Create Date: 2020-07-19 10:50:17.855411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aec1333954f'
down_revision = '42535c6e4ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', sa.LargeBinary(length=16777215), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file')
    # ### end Alembic commands ###
