"""Changed File file 

Revision ID: 42535c6e4ab1
Revises: 7ea710fe5e78
Create Date: 2020-07-19 10:47:46.796511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42535c6e4ab1'
down_revision = '7ea710fe5e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
