"""Changed File file 

Revision ID: 7ea710fe5e78
Revises: 22627e9d9e06
Create Date: 2020-07-19 10:45:39.859518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea710fe5e78'
down_revision = '22627e9d9e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file')
    # ### end Alembic commands ###
