"""added filename to files table

Revision ID: 945ab8b6f9c5
Revises: 5670f91fe832
Create Date: 2020-07-17 01:20:45.004581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945ab8b6f9c5'
down_revision = '5670f91fe832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'filename')
    # ### end Alembic commands ###
