"""added expire_at to files table

Revision ID: f459f947512b
Revises: 945ab8b6f9c5
Create Date: 2020-07-17 09:38:10.313054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f459f947512b'
down_revision = '945ab8b6f9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('expire_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'expire_at')
    # ### end Alembic commands ###
